// This file is automatically generated. Do not edit.
export const firebaseConfig = {
  apiKey: 'AIzaSyCBhtbiiVS5SsJn-N00gbM1oX625BjI3YM',
  authDomain: 'autosubscription-6c04a.firebaseapp.com',
  projectId: 'autosubscription-6c04a',
  storageBucket: 'autosubscription-6c04a.appspot.com',
  messagingSenderId: '688217735729',
  appId: '1:688217735729:web:d33661bd523a425e374b10',
};
